"""CLI: compile briefs and record images generated by the Codex host."""
import argparse
import json
import logging
import sys
from pathlib import Path

from .config import Config
from .planner import compile_brief
from .tools import error_action, record_image, validate_references
from .utils import BriefError, load_json, write_json

ROOT = Path(__file__).resolve().parents[1]


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description="电商图片编排/验收 CLI；真实生图由 Codex 内置 image_gen 执行")
    parser.add_argument("--config", type=Path, default=ROOT / "config.json")
    sub = parser.add_subparsers(dest="command", required=True)
    plan = sub.add_parser("plan")
    plan.add_argument("--brief", type=Path, required=True)
    plan.add_argument("--out", type=Path, required=True)
    record = sub.add_parser("record")
    record.add_argument("--manifest", type=Path, required=True)
    record.add_argument("--asset", required=True)
    record.add_argument("--image", type=Path, required=True)
    record.add_argument("--qa", type=Path, required=True)
    record.add_argument("--out", type=Path, required=True)
    error = sub.add_parser("error")
    error.add_argument("--kind", required=True)
    error.add_argument("--attempt", type=int, default=0)
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        cfg = Config.load(args.config)
        if args.command == "plan":
            brief = load_json(args.brief, cfg.max_input_bytes)
            result = compile_brief(brief, args.brief.resolve().parent, cfg)
            validate_references(result, cfg)
            args.out.mkdir(parents=True, exist_ok=False)
            write_json(args.out / "brief.json", brief)
            write_json(args.out / "manifest.json", result)
            for asset in result["assets"]:
                (args.out / (asset["id"] + ".prompt.txt")).write_text(asset["tool_args"]["prompt"], encoding="utf-8")
            print(json.dumps({"status": "planned", "assets": len(result["assets"]), "manifest": str((args.out / "manifest.json").resolve()), "next": "Codex must call image_gen with each tool_args"}, ensure_ascii=False))
        elif args.command == "record":
            result = record_image(load_json(args.manifest, cfg.max_input_bytes * 10), args.asset, args.image,
                                  load_json(args.qa, cfg.max_input_bytes), args.out, cfg)
            print(json.dumps(result, ensure_ascii=False))
            return 0 if result["status"] == "accepted" else 3
        else:
            print(json.dumps(error_action(args.kind, args.attempt, cfg), ensure_ascii=False))
        return 0
    except (BriefError, ValueError, OSError, KeyError, TypeError) as exc:
        logging.error("%s: %s", type(exc).__name__, exc)
        print(json.dumps({"status": "error", "type": type(exc).__name__, "message": str(exc)}, ensure_ascii=False))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
